import React, { createContext, useContext, useState, useEffect } from 'react'

export type Lang = 'en' | 'zh'

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Layout
    'nav.config': 'Config',
    'nav.scan': 'Scan',
    'settings.language': 'Language',
    'settings.title': 'Settings',
    // Config
    'config.title': 'Configuration',
    'config.llmProvider': 'LLM Provider',
    'config.apiKey': 'API Key',
    'config.apiKeySet': 'API key is already saved. Enter a new key to overwrite.',
    'config.apiKeyPlaceholder': 'sk-...',
    'config.apiKeySetPlaceholder': '•••••• (already set - leave blank to keep)',
    'config.model': 'Model',
    'config.baseUrl': 'Base URL (for OpenAI-compatible APIs)',
    'config.baseUrlPlaceholder': 'Leave empty for default',
    'config.maxTokens': 'Max Tokens',
    'config.projectRoot': 'Project Root Directory',
    'config.save': 'Save Config',
    'config.saving': 'Saving...',
    'config.goScan': 'Go to Scan',
    'config.saved': 'Configuration saved successfully',
    'common.loading': 'Loading...',
    'common.error': 'Error:',
    // Scan
    'scan.title': 'Project Scan',
    'scan.viewResults': 'View Results',
    'scan.newScan': 'New Scan',
    'scan.scanProject': 'Scan Project',
    'scan.scanning': 'Scanning...',
    'scan.projectRoot': 'Project Root',
    'scan.projectRootRequired': 'Project root is required',
    'scan.failed': 'Scan failed',
    'scan.noFiles': 'No C++ source files found. Please check the project path.',
    'scan.prevFailed': 'Previous scan failed. Start a new scan.',
    'scan.loadingData': 'Loading scan data...',
    'scan.scanningFiles': 'Scanning project files... Please wait.',
    'scan.noData': 'No scan data available for this scan.',
    'scan.viewReport': 'View Report',
    'scan.startNew': 'Start a New Scan',
    'scan.modules': 'Modules',
    'scan.deselectAll': 'Deselect All',
    'scan.selectAll': 'Select All',
    'scan.files': 'files',
    'scan.deps': 'deps',
    'scan.issues': 'issues',
    'scan.fileTree': 'Files',
    'scan.lines': 'lines',
    'scan.analyze': 'Analyze {count} Modules',
    'scan.starting': 'Starting...',
    'scan.status': 'Status',
    'scan.tokens': 'tokens',
    'scan.importReport': 'Import Report',
    'scan.importTitle': 'Import Analysis Report',
    'scan.importHint': 'Paste the analysis report JSON below, or load from a file. The report is generated by Claude Code / other tools.',
    'scan.importPlaceholder': 'Paste report JSON here...',
    'scan.importFile': 'Load from file',
    'scan.importBtn': 'Import',
    'scan.importCancel': 'Cancel',
    'scan.importSuccess': 'Imported {count} issues successfully',
    'scan.importAlreadyFixed': '{count} already fixed, skipped',
    'scan.importAllFixed': 'All {count} issues already fixed, nothing to import',
    'scan.importError': 'Import failed',
    // Analysis
    'analysis.title': 'Analysis Progress',
    'analysis.modules': 'Modules: {done}/{total}',
    'analysis.current': 'Current: {name}',
    'analysis.status': 'Status: {status}',
    'analysis.files': 'Files: {done}/{total}',
    'analysis.issuesFound': 'Issues found: {count}',
    'analysis.complete': 'Analysis Complete',
    'analysis.issuesTotal': '{count} issues found',
    'analysis.viewResults': 'View Results',
    'analysis.log': 'Log',
    // Results
    'results.title': 'Analysis Results',
    'results.total': 'Total:',
    'results.allSeverities': 'All severities',
    'severity.critical': 'Critical',
    'severity.high': 'High',
    'severity.medium': 'Medium',
    'severity.low': 'Low',
    'category.memory_safety': 'Memory Safety',
    'category.concurrency': 'Concurrency',
    'category.exception_safety': 'Exception Safety',
    'category.modern_cpp': 'Modern C++',
    'category.code_style': 'Code Style',
    'category.type_safety': 'Type Safety',
    'category.undefined_behavior': 'Undefined Behavior',
    'category.performance': 'Performance',
    'category.other': 'Other',
    'results.allStatus': 'All status',
    'status.pending': 'Pending',
    'status.applied': 'Applied',
    'status.rejected': 'Rejected',
    'status.failed': 'Failed',
    'scanStatus.completed': 'Completed',
    'scanStatus.scanning': 'Scanning',
    'scanStatus.pending': 'Pending',
    'scanStatus.analyzing': 'Analyzing',
    'scanStatus.failed': 'Failed',
    'results.hint': 'Click Accept to immediately apply the fix to source code',
    'results.noIssues': 'No issues found',
    'results.acceptApply': 'Accept & Apply Fix',
    'results.reject': 'Reject',
    'results.revert': 'Revert Fix',
    'results.retry': 'Retry',
    'results.undo': 'Undo',
    'results.file': 'File:',
    'results.line': 'Line:',
    'results.category': 'Category:',
    'results.rule': 'Rule:',
    'results.suggestedFix': 'Suggested Fix:',
    'results.appliedChange': 'Applied Change:',
    'results.selectIssue': 'Select an issue to view details',
    'results.applied': 'Fix applied successfully',
    'results.rejected': 'Issue rejected',
    'results.reverted': 'Fix reverted',
    'results.failedApply': 'Failed:',
    'results.loading': 'Loading issues...',
    'results.lineLabel': 'Line {start}{end}',
    'results.exportReport': 'Export Report',
    'results.exported': 'Report exported',
  },
  zh: {
    // Layout
    'nav.config': '配置',
    'nav.scan': '扫描',
    'settings.language': '语言',
    'settings.title': '设置',
    // Config
    'config.title': '配置',
    'config.llmProvider': '模型供应商',
    'config.apiKey': 'API 密钥',
    'config.apiKeySet': 'API 密钥已保存，输入新密钥可覆盖',
    'config.apiKeyPlaceholder': 'sk-...',
    'config.apiKeySetPlaceholder': '••••••（已设置 - 留空则保留）',
    'config.model': '模型',
    'config.baseUrl': 'Base URL（OpenAI 兼容接口）',
    'config.baseUrlPlaceholder': '留空使用默认值',
    'config.maxTokens': '最大 Token 数',
    'config.projectRoot': '项目根目录',
    'config.save': '保存配置',
    'config.saving': '保存中...',
    'config.goScan': '前往扫描',
    'config.saved': '配置保存成功',
    'common.loading': '加载中...',
    'common.error': '错误：',
    // Scan
    'scan.title': '项目扫描',
    'scan.viewResults': '查看结果',
    'scan.newScan': '新建扫描',
    'scan.scanProject': '扫描项目',
    'scan.scanning': '扫描中...',
    'scan.projectRoot': '项目根目录',
    'scan.projectRootRequired': '请输入项目根目录',
    'scan.failed': '扫描失败',
    'scan.noFiles': '未找到 C++ 源文件，请检查项目路径。',
    'scan.prevFailed': '上次扫描失败，请重新扫描',
    'scan.loadingData': '加载扫描数据...',
    'scan.scanningFiles': '正在扫描项目文件，请稍候...',
    'scan.noData': '此扫描没有可用数据',
    'scan.viewReport': '查看报告',
    'scan.startNew': '开始新扫描',
    'scan.modules': '模块',
    'scan.deselectAll': '全不选',
    'scan.selectAll': '全选',
    'scan.files': '个文件',
    'scan.deps': '个依赖',
    'scan.issues': '个问题',
    'scan.fileTree': '文件',
    'scan.lines': '行',
    'scan.analyze': '分析 {count} 个模块',
    'scan.starting': '启动中...',
    'scan.status': '状态',
    'scan.tokens': 'tokens',
    'scan.importReport': '导入报告',
    'scan.importTitle': '导入分析报告',
    'scan.importHint': '在下方粘贴分析报告 JSON，或从文件加载。报告由 Claude Code 等工具生成。',
    'scan.importPlaceholder': '在此粘贴报告 JSON...',
    'scan.importFile': '从文件加载',
    'scan.importBtn': '导入',
    'scan.importCancel': '取消',
    'scan.importSuccess': '成功导入 {count} 个问题',
    'scan.importAlreadyFixed': '，{count} 个已修复，已跳过',
    'scan.importAllFixed': '所有 {count} 个问题均已修复，无需导入',
    'scan.importError': '导入失败',
    // Analysis
    'analysis.title': '分析进度',
    'analysis.modules': '模块：{done}/{total}',
    'analysis.current': '当前：{name}',
    'analysis.status': '状态：{status}',
    'analysis.files': '文件：{done}/{total}',
    'analysis.issuesFound': '发现问题：{count}',
    'analysis.complete': '分析完成',
    'analysis.issuesTotal': '发现 {count} 个问题',
    'analysis.viewResults': '查看结果',
    'analysis.log': '日志',
    // Results
    'results.title': '分析结果',
    'results.total': '总计：',
    'results.allSeverities': '所有严重程度',
    'severity.critical': '严重',
    'severity.high': '高',
    'severity.medium': '中',
    'severity.low': '低',
    'category.memory_safety': '内存安全',
    'category.concurrency': '并发',
    'category.exception_safety': '异常安全',
    'category.modern_cpp': '现代 C++',
    'category.code_style': '代码风格',
    'category.type_safety': '类型安全',
    'category.undefined_behavior': '未定义行为',
    'category.performance': '性能',
    'category.other': '其他',
    'results.allStatus': '所有状态',
    'status.pending': '待处理',
    'status.applied': '已应用',
    'status.rejected': '已拒绝',
    'status.failed': '失败',
    'scanStatus.completed': '已完成',
    'scanStatus.scanning': '扫描中',
    'scanStatus.pending': '待处理',
    'scanStatus.analyzing': '分析中',
    'scanStatus.failed': '失败',
    'results.hint': '点击接受即可立即应用修复到源码',
    'results.noIssues': '未发现问题',
    'results.acceptApply': '接受并应用修复',
    'results.reject': '拒绝',
    'results.revert': '撤销修复',
    'results.retry': '重试',
    'results.undo': '撤销',
    'results.file': '文件：',
    'results.line': '行：',
    'results.category': '类别：',
    'results.rule': '规则：',
    'results.suggestedFix': '建议修复：',
    'results.appliedChange': '已应用的修改：',
    'results.selectIssue': '选择问题查看详情',
    'results.applied': '修复已应用',
    'results.rejected': '问题已拒绝',
    'results.reverted': '修复已撤销',
    'results.failedApply': '失败：',
    'results.loading': '加载问题中...',
    'results.lineLabel': '第 {start} 行{end}',
    'results.exportReport': '导出报告',
    'results.exported': '报告已导出',
  },
}

interface I18nContextValue {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const I18nContext = createContext<I18nContextValue>({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
})

const LANG_STORAGE_KEY = 'cpp_inspector_lang'

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const saved = localStorage.getItem(LANG_STORAGE_KEY)
      return (saved === 'zh' || saved === 'en') ? saved as Lang : 'en'
    } catch { return 'en' }
  })

  useEffect(() => {
    try { localStorage.setItem(LANG_STORAGE_KEY, lang) } catch {}
  }, [lang])

  const setLang = (l: Lang) => setLangState(l)

  const t = (key: string, params?: Record<string, string | number>) => {
    let str = translations[lang][key] ?? translations.en[key] ?? key
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        str = str.replace(`{${k}}`, String(v))
      }
    }
    return str
  }

  return (
    <I18nContext.Provider value={{ lang, setLang, t }}>
      {children}
    </I18nContext.Provider>
  )
}

export function useI18n() {
  return useContext(I18nContext)
}
